language: python
sudo: false
dist: xenial
#services:
#  - xvfb

#python:
#  - "3.5"
#  - "3.6"
#  - "3.7"

matrix:
  include:

    - name: "Python 3.5 on Xenial Linux"
      python: 3.5
      services: xvfb
      install: pip install -r requirements.txt
      script: pytest

    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      services: xvfb
      install: pip install -r requirements.txt
      script: pytest

    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      services: xvfb
      install: pip install -r requirements.txt
      script: pytest

    # ======= OSX ========
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: generic       # 'language: python' is an error on Travis CI macOS
#      env:
#        - XQUARTZ_VERSION=2.7.7
      before_install:
#        - curl -L -O http://xquartz.macosforge.org/downloads/SL/XQuartz-${XQUARTZ_VERSION}.dmg
#        - hdiutil mount XQuartz-${XQUARTZ_VERSION}.dmg
#        - sudo installer -store -pkg /Volumes/XQuartz-${XQUARTZ_VERSION}/XQuartz.pkg -target /
#        - hdiutil unmount /Volumes/XQuartz-${XQUARTZ_VERSION}
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
      install: pip3 install -r requirements.txt
      script: python3 -m pytest

#    - name: "Python 3.7.3 on macOS 10.14"
#      os: osx
#      osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
#      language: shell       # 'language: python' is an error on Travis CI macOS
#      before_install:
#        - python3 --version
#        - pip3 install -U pip
#        - pip3 install -U pytest
#        - pip3 install codecov
#      script: python3 -m pytest
#      after_success: python3 -m codecov
    - name: "Python 3.7.4 on macOS 10.14"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: generic       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
      install: pip3 install -r requirements.txt
      script: python3 -m pytest

    #  ====== WINDOWS =========
#    - name: "Python 3.5.4 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python --version 3.5.4
#        - python --version
#        - python -m pip install --upgrade pip
#        - pip3 install --upgrade pytest
#        - pip3 install codecov
#      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
#      install: pip3 install -r requirements.txt
#      script: python -m pytest
#    - name: "Python 3.6.8 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python --version 3.6.8
#        - python --version
#        - python -m pip install --upgrade pip
#        - pip3 install --upgrade pytest
#        - pip3 install codecov
#      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
#      install: pip3 install -r requirements.txt
#      script: python -m pytest
#    - name: "Python 3.7.4 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python --version 3.7.4
#        - python --version
#        - python -m pip install --upgrade pip
#        - pip3 install --upgrade pytest
#        - pip3 install codecov
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
#      install: pip3 install -r requirements.txt
#      script: python -m pytest

# command to install dependencies
#install:
#  - pip install -r requirements.txt

# command to run tests
#script:
#  - pytest

#after_success:
#  # Upload coverage data to codecov
#  - codecov