language: python
sudo: false
dist: xenial
#services:
#  - xvfb

#python:
#  - "3.5"
#  - "3.6"
#  - "3.7"

matrix:
  include:

    - name: "Python 3.5.6 on Xenial Linux"
      python: 3.5
      services: xvfb
#      install: pip install -r requirements.txt
#      script: pytest
      env: OS="linux"

    - name: "Python 3.6.7 on Xenial Linux"
      python: 3.6
      services: xvfb
#      install: pip install -r requirements.txt
#      script: pytest
      env: OS="linux"

    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
      services: xvfb
#      install: pip install -r requirements.txt
#      script: pytest
      env: OS="linux"

    # ======= OSX ========
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4
      language: generic
#      before_install:
#        - python3 --version
#        - pip3 install -U pip
#        - pip3 install -U pytest
#        - pip3 install codecov
#      install: pip3 install -r requirements.txt
#      script: python3 -m pytest
      env: OS="osx"

    - name: "Python 3.7.4 on macOS 10.14"
      os: osx
      osx_image: xcode11
      language: generic
#      before_install:
#        - python3 --version
#        - pip3 install -U pip
#        - pip3 install -U pytest
#        - pip3 install codecov
#      install: pip3 install -r requirements.txt
#      script: python3 -m pytest
      env: OS="osx"

    #  ====== WINDOWS =========
#    - name: "Python 3.5.4 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python --version 3.5.4
#        - python --version
#        - python -m pip install --upgrade pip
#        - pip3 install --upgrade pytest
#        - pip3 install codecov
#      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
#      install: pip3 install -r requirements.txt
#      script: python -m pytest
#    - name: "Python 3.6.8 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python --version 3.6.8
#        - python --version
#        - python -m pip install --upgrade pip
#        - pip3 install --upgrade pytest
#        - pip3 install codecov
#      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
#      install: pip3 install -r requirements.txt
#      script: python -m pytest
#    - name: "Python 3.7.4 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python --version 3.7.4
#        - python --version
#        - python -m pip install --upgrade pip
#        - pip3 install --upgrade pytest
#        - pip3 install codecov
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
#      install: pip3 install -r requirements.txt
#      script: python -m pytest


before_install:
  - if [[ "$OS" == "linux" ]]; then
    false

    elif [[ "$OS" == "osx" ]]; then
      python3 --version
      pip3 install -U pip
      pip3 install -U pytest
      pip3 install codecov
    fi


# command to install dependencies
install:
  - if [[ "$OS" == "linux" ]]; then
      pip install -r requirements.txt
    elif [[ "$OS" == "osx" ]]; then
      pip3 install -r requirements.txt
    fi


# command to run tests
script:
  - if [[ "$OS" == "linux" ]]; then
    pytest
  elif [[ "$OS" == "osx" ]]; then
    python3 -m pytest
  fi

#after_success:
#  # Upload coverage data to codecov
#  - codecov