language: python
sudo: false
dist: xenial


matrix:
  include:

    - name: "Python 3.5.6 on Xenial Linux"
      python: 3.5
      services: xvfb

    - name: "Python 3.6.7 on Xenial Linux"
      python: 3.6
      services: xvfb

    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
      services: xvfb
      env: REPORT_COVERAGE=true

    # ======= OSX ========
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4
      language: generic

    - name: "Python 3.7.4 on macOS 10.14"
      os: osx
      osx_image: xcode11
      language: generic


before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      python3 --version;
      pip3 install -U pip;
    else
      python --version;
      pip install -U pip;
    fi


# command to install dependencies
install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      pip3 install -e ".[test]";
    else
      pip install -e ".[test]";
    fi


# command to run tests
script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      python3 -m pytest;
    else
      pytest;
    fi


after_success:
  # Upload coverage data to codecov
  - if [[ "$REPORT_COVERAGE" == "true" ]]; then
      echo "Uploading coverage to Codecov";
      codecov;
    fi